gap/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'gap'



pregunta_urlpatterns = [
    path('', views.PreguntaListView.as_view(), name='pregunta_list'),
    path('new', views.PreguntaCreate.as_view(), name='pregunta_new'),
    path('edit/<int:pk>', views.PreguntaUpdate.as_view(), name='pregunta_edit'),
    path('<int:pk>', views.PreguntaDetailView.as_view(), name='pregunta_detail'),
    path('delete/<int:pk>', views.PreguntaDelete.as_view(), name='pregunta_delete'),
]

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('responsables/', views.Responsables, name='responsables'),
    path('preguntas/', include(pregunta_urlpatterns)),
    path('carga_usuario/', views.CargaUsuario.as_view(), name='carga_usuario'),
    path('singleuser/', views.empleado_create, name='carga_usuario_singular'),
    path('multipleuser/', views.CargaMasivaUsuario, name='carga_usuario_masiva'),
    path('parametros/<int:pk>', views.ParametrosUpdate.as_view(), name='parametros'),
    path('resultados/', views.Resultados, name='Resultados'),
    path('homencuestas/<int:pk>', views.homecuestas, name='homecuestas'),
    path('encuesta/<int:enc_pk>/<int:dom_pk>', views.encuesta, name='encuesta'),
    path('exportResultados/<int:pk>/', views.Returnexcelresultados, name='exportResultados'),
    path('recomendaciones/', views.Recomendaciones, name='recomendaciones'),
    path('informe/<int:pk>/', views.generarInforme, name='informe'),
    path('plandeaccion/<int:pk>/', views.generarPlanDeAccion, name='PlanDeAccion'),
    path('crearencuesta/', views.EncuestaCreate, name='CrearEncuesta'),
    path('graficos/', views.Graficos, name='Graficos'),
    path('encuestas/', views.EncuestasShow, name='EncuestasShow'),
    path('preguntascarga/', views.CargaMasivaPregunta, name='preguntas'),

]

seguridad/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gap/', include('gap.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/gap/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gap/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import *
from crispy_forms.helper import FormHelper
from django import forms


class PreguntaForm(ModelForm):
    class Meta:
        model = Pregunta
        fields = '__all__'


class EmpleadoForm(ModelForm):
    class Meta:
        model = Empleado
        fields = '__all__'



class EncuestaForm(ModelForm):

    class Meta:
        model = Encuesta
        fields = '__all__'
        widgets = {
            'fecha_inicio': forms.DateInput(attrs={'class': 'datepicker', 'id': 'data_input'}),
            'fecha_termino': forms.DateInput(attrs={'class': 'datepicker2', 'id': 'data_input'}),
            'empleados': forms.CheckboxSelectMultiple,
        }


class DominioForm(ModelForm):
    class Meta:
        model = Dominio
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(DominioForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        if self.instance.id:
            self.fields['nombre'].widget.attrs['readonly'] = True


class ParametrosForm(ModelForm):
    class Meta:
        model = Parametros
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ParametrosForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False 

class ExtendUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            # 'first_name',
            # 'last_name',
            'password1',
            'password2',
        )
    def save(self, commit=True):
        user = super().save(commit=True)

        user.email = self.cleaned_data['email']
        # user.first_name = self.cleaned_data['first_name']
        # user.last_name = self.cleaned_data['last_name'] 

        if commit:
            user.save()
        else:
            print("no save pero save iwal")
            user.save()
        return user

class UserEmpleadoExtend(forms.ModelForm):
    class Meta:
        model = Empleado

        fields = (
            'primer_nombre',
            'segundo_nombre',
            'apellido_materno',
            'apellido_paterno',
            # 'email',
            'rut',
            'cargo',
            'sucursal',
            'tipo',
        )
        
        # self.helper.form_show_labels = False


CHOICES = (
    ('s', 'Si'),
    ('n', 'No'),
    ('d', 'Desconozco'),
)


class AnswerForm(ModelForm):
    choice_text = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect())

    class Meta:
        model = Alternativas
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AnswerForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False

gap/views.py
from django.views.generic.base import TemplateView
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
import logging
import string
from datetime import timedelta
import numpy
import xlwt
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.db.models import Count
from django.forms import modelformset_factory
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import Permission
from django.contrib.auth import authenticate
from .models import(
                    Departamento,
                    Sucursal,
                    Empleado,
                    Pregunta,
                    Alternativas,
                    Parametros,
                    Dominio
                )
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.base import TemplateView
from django.template.loader import render_to_string

from weasyprint import HTML

from .forms import *


# Create your views here.

class Home(TemplateView):
    template_name = "gap/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['latest_articles'] = Article.objects.all()[:5] example
        return context


# Opciones de carga de usuario
class CargaUsuario(TemplateView):
    template_name = 'gap/carga_usuario.html'
    
def empleado_create(request):
    template = 'gap/carga_usuario_singular.html'

    if request.method == "POST":
        form = ExtendUserCreationForm(request.POST)
        empleado_extend = UserEmpleadoExtend(request.POST)

        if form.is_valid() and empleado_extend.is_valid():
            user = form.save()
            
            content_type = ContentType.objects.get_for_model(Empleado)
            # permission = Permission.objects.get(
            #         codename='is_employ',
            #         content_type=content_type,
            #     )
            # user.user_permissions.add(permission)
                
            employ_profile = empleado_extend.save(commit=False)
            employ_profile.user = user
        
            employ_profile.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=password)


            return redirect('gap:carga_usuario')
       
    else:
        form = ExtendUserCreationForm()
        empleado_extend = UserEmpleadoExtend()
    
    context = {
        'form': form,
        'empleado_extend': empleado_extend,
    }
    return render(request, template, context)       


class SingleUser(generic.CreateView):
    model = Empleado
    fields = ['primer_nombre', 'segundo_nombre', 'apellido_materno', 'apellido_paterno', 'email', 'rut', 'cargo',
              'sucursal', 'tipo']
    success_url = reverse_lazy('gap:home')
    template_name = 'gap/carga_usuario_singular.html'


# Carga Usuario Masiva
def CargaMasivaUsuario(request):
    data = {}
    error = False
    if "GET" == request.method:
        return render(request, "gap/carga_usuario_masiva.html", data)
    # if not GET, then proceed
    try:
        csv_file = request.FILES["file"]
        if not csv_file.name.endswith('.csv'):
            messages.error(request, 'Archivo no es de formato CSV')
            error = True;
            return HttpResponseRedirect(reverse_lazy("gap:carga_usuario_masiva"))
        # if file is too large, return
        if csv_file.multiple_chunks():
            messages.error(request, "Archivo es excede el peso permitido (%.2f MB)." % (csv_file.size / (1000 * 1000),))
            error = True;
            return HttpResponseRedirect(reverse_lazy("gap:carga_usuario_masiva"))

        file_data = csv_file.read().decode("utf-8")

        lines = file_data.split("\n")
        lines = iter(lines)
        # loop over the lines and save them in db. If error , store as string and then display
        next(lines)
        for line in lines:
            if line:
                line = line.replace('\r', '')
                fields = line.split(";")
                data_dict = {"primer_nombre": fields[0], "segundo_nombre": fields[1], "apellido_materno": fields[2],
                             "apellido_paterno": fields[3], "email": fields[4], "rut": fields[5], "cargo": fields[6]}
                sucursal = Sucursal.objects.get(name=fields[7])
                data_dict["sucursal"] = sucursal.pk
                if fields[8] == 'Director':
                    field_8 = 'd'
                elif fields[8] == 'Operativo':
                    field_8 = 'o'
                elif fields[8] == 'Director-Operativo':
                    field_8 = 'do'
                else:
                    field_8 = 'nn'
                data_dict["tipo"] = field_8
                try:
                    form = EmpleadoForm(data_dict)
                    if form.is_valid():
                        form.save()
                    else:
                        messages.error(request,
                                       'Al menos uno de los empleados ingresados contiene un error en los campos')
                        error = True;
                        logging.getLogger("error_logger").error(form.errors.as_json())
                except Exception as e:
                    messages.error(request, 'Existio un error en el sistema')
                    error = True;
                    logging.getLogger("error_logger").error(form.errors.as_json())
                    pass

    except Exception as e:
        logging.getLogger("error_logger").error("Unable to upload file. " + repr(e))
        error = True;
        messages.error(request, "No se puede subir el archivo " + repr(e))
    if not error:
        messages.success(request, 'Success')
    return HttpResponseRedirect(reverse_lazy("gap:carga_usuario_masiva"))


# Crear Preguntas
class PreguntaListView(generic.ListView):
    model = Pregunta
    queryset = Pregunta.objects.all()
    paginate_by = 10


class PreguntaDetailView(generic.DetailView):
    model = Pregunta
    queryset = Pregunta.objects.all()


class PreguntaCreate(generic.CreateView):
    model = Pregunta
    form_class = PreguntaForm
    success_url = reverse_lazy('pregunta_list')


class PreguntaUpdate(generic.UpdateView):
    model = Pregunta
    form_class = PreguntaForm
    success_url = reverse_lazy('pregunta_list')


class PreguntaDelete(generic.DeleteView):
    model = Pregunta
    success_url = reverse_lazy('pregunta_list')


def Responsables(request):
    FormSet = modelformset_factory(Dominio, extra=0, form=DominioForm)
    if request.method == 'POST':
        form = FormSet(request.POST)
        if form.is_valid():
            form.save()
    context = FormSet()
    return render(request, "gap/responsables.html", {'formset': context})


class ParametrosUpdate(generic.UpdateView):
    model = Parametros
    form_class = ParametrosForm
    success_url = reverse_lazy('gap:home')


def Resultados(request):
    encuestas = Encuesta.objects.all()
    if request.method == 'POST':
        dominios = Dominio.objects.all()
        encuesta = Encuesta.objects.get(pk=request.POST.get("selectorencuesta", ""))
        encuestahasdoms = EncuestaHasDominio.objects.filter(encuesta=encuesta)
        Empleados = Empleado.objects.all()
        Empleados_count = Empleado.objects.all().count()
        query = RespuestasEncabezado.objects \
            .values('empleado', 'encuesta_has_dominio__dominio') \
            .annotate(Count('alternativas')) \
            .filter(encuesta_has_dominio__in=encuestahasdoms)
        queryDom2 = RespuestasEncabezado.objects \
            .values('empleado') \
            .annotate(Count('alternativas')) \
            .filter(encuesta_has_dominio__in=encuestahasdoms, encuesta_has_dominio__dominio_id=2)
        arr = numpy.zeros((Empleados_count, 11), numpy.int8)
        n = 0
        for empleado in Empleados:
            for x in query:
                if x['empleado'] == empleado.id:
                    if x['encuesta_has_dominio__dominio'] == 1:
                        arr[n][0] = x['alternativas__count']
                    if x['encuesta_has_dominio__dominio'] == 2:
                        arr[n][1] = x['alternativas__count']
                    if x['encuesta_has_dominio__dominio'] == 3:
                        arr[n][2] = x['alternativas__count']
                    if x['encuesta_has_dominio__dominio'] == 4:
                        arr[n][3] = x['alternativas__count']
                    if x['encuesta_has_dominio__dominio'] == 5:
                        arr[n][4] = x['alternativas__count']
                    if x['encuesta_has_dominio__dominio'] == 6:
                        arr[n][5] = x['alternativas__count']
                    if x['encuesta_has_dominio__dominio'] == 7:
                        arr[n][6] = x['alternativas__count']
                    if x['encuesta_has_dominio__dominio'] == 8:
                        arr[n][7] = x['alternativas__count']
                    if x['encuesta_has_dominio__dominio'] == 9:
                        arr[n][8] = x['alternativas__count']
                    if x['encuesta_has_dominio__dominio'] == 10:
                        arr[n][9] = x['alternativas__count']
                    if x['encuesta_has_dominio__dominio'] == 11:
                        arr[n][10] = x['alternativas__count']
            n += 1

        union = zip(Empleados, arr)
        context = {
            'dominios': dominios,
            'query': query,
            'union': union,
            'encuestas': encuestas,
            'encuesta': encuesta,
        }
        return render(request, "gap/resultados_list.html", context)

    context = {

gap/templates/gap/carga_pregunta_masiva.html
{% extends 'gap/base.html' %}
{{order}}
{% load bootstrap4 %}
{% block content %}

<div class="container">
{% if messages %}
	{% for message in messages%}
		<div>
			{% if message.tags == "error" %}
				<div class="alert alert-danger" role="alert">
	  			Existio un error <strong>{{message|safe}}</strong> , por favor intentelo denuevo
				</div>
			{% endif %}
			{% if message.tags == "success" %}
				<div class="alert alert-success" role="alert">
	  			La acción se completo satisfactoriamente
				</div>
			{% endif %}	
		</div>
	{% endfor %}
{% endif %}
	
	    <form method="post" enctype="multipart/form-data">
	    <div class="card">
		  <h5 class="card-header">Carga de Empleados Masiva</h5>
		  <div class="card-body">
		    <p class="card-text">Porfavor subir archivo csv con el formato.</p>
		    <label> Subir un archivo </label>
	        <input type="file" name="file">
	        <div class="col text-right">
		        <a class="btn btn-primary" href="{% url 'gap:carga_usuario_masiva' %}" role="button">Limpiar</a>
		        {% load static %}
		        <a class="btn btn-primary" href="{% static "gap/template.csv" %}" role="button">Descargar Formato</a>
		        <button type="submit" class="btn btn-primary"> Enviar</button>
	    	</div>
		  </div>
	        {% csrf_token %}

	        <!-- {{ form.as_p }} -->
	     </div>
	    </form> 
	</div>
{% endblock %}

gap/templates/gap/carga_usuario.html
{% extends 'gap/base.html' %}
{% load bootstrap4 %}



{% block content %}

<main role="main" class="inner cover text-center">
  <h1 class="cover-heading">Carga de usuarios.</h1>
  <p class="lead">
    <a href="{% url 'gap:carga_usuario_singular' %}" class="btn btn-lg btn-secondary">Singular</a>
  </p>
  <p class="lead">
    <a href="{% url 'gap:carga_usuario_masiva' %}" class="btn btn-lg btn-secondary">Masiva</a>
  </p>
</main>
{% endblock  %}
    

gap/templates/gap/d3_encuestas.html
<html>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <heat>
        <title>
            Formulario test
        </title>
    </heat>
    <body>
        <header>
            <b>Formulario prueba 1</b>
        </header>
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <p class="font-weight-normal">
                        Preguntas.
                    </p>
                </div>
                <div class="col-4">
                    <p class="font-weight-normal">
                        Respuestas.
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-8">
                    Pagina de pruebas para formulario
                </div>
                <form method="POST"> 
                {% csrf_token %}
                {% for radio in fields %}
                <label >
                {{ radio }}
                 <span> {{ radio.tag }} </span>
                 </label>

                {% endfor %}
                <input type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </body>
    <footer>
        <a href="{% url 'gap:homecuestas' %}" class="btn btn-primary">Volver a encuestas</a>
    </footer>
</html>

gap/templates/gap/d4_encuestas.html
<html>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <heat>
        <title>
            Formulario test
        </title>
    </heat>
    <body>
        <header>
            <b>Formulario prueba 4</b>
        </header>
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <p class="font-weight-normal">
                        Preguntas.
                    </p>
                </div>
                <div class="col-4">
                    <p class="font-weight-normal">
                        Respuestas.
                    </p>
                </div>
            </div>
            {% block content %}
            <form method="POST" class="post-form">
            {% csrf_token %}
            <h2>Cosa que agregue para guardar la cosa del form</h2>
            {{ form.as_p }}
            <div class="row">
                <div class="col-8">
                    Pagina de prueba
                </div>
                <div class="col-4">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios8" id="exampleRadios1" value="option1">
                        <label class="form-check-label" for="exampleRadios1">
                          Si
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios8" id="exampleRadios2" value="option2">
                        <label class="form-check-label" for="exampleRadios2">
                          No
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="exampleRadios8" id="exampleRadios3" value="option3">
                        <label class="form-check-label" for="exampleRadios3">
                          Desconoce
                        </label>
                    </div>
                </div>
            </div>
            <button type="submit" class="save btn btn-default">Save</button>
            </form>
            {% endblock %}
        </div>
    </body>
    <footer>
        <a href="{% url 'gap:homecuestas' %}" class="btn btn-primary">Volver a encuestas</a>
    </footer>
</html>

gap/templates/gap/encuesta_form.html
{% extends 'gap/base.html' %}
{% load bootstrap4 %}


{% block content %}
<div class="container">
    <h1 class="text-center">Crear Encuesta</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary" ></i> Enviar</button>
    </form>
</div>

    <script>
  $(function () {
      $('.datepicker').datepicker()
      $('.datepicker2').datepicker()
  });
</script>
{% endblock %}

gap/templates/gap/encuestas.html
{% extends 'gap/base.html' %}
{% load static %}

{% load bootstrap4 %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <form method="post" enctype="multipart/form-data">
    	<div class="card">
		  <h5 class="card-header">{{ qname.nombre }}</h5>
		  <div class="card-body">
    		{% csrf_token %}
    		{{ answer_formset.management_form }}
			{% for Pregunta, form in combined %}
			<div class="row">
				{{ form.question.as_hidden }}
				{{ form.Encabezado.as_hidden }}
                {{ form.creacion.as_hidden }}
				{% for hidden in form.hidden_fields %}
        			{{ hidden }}
    			{% endfor %}
				<div class="col-6">
					{{ Pregunta }}
	      		</div>
	      		<div class="col-6">
	        	{{ form.choice_text|as_crispy_field }}
	      		</div>
    		</div>
			{% endfor %}
			<div class="row">
    		<div class="col-12 text-right">
        		<button type="submit" class="btn btn-primary"> Actualizar</button>
        	</div>
    	</div>
    	</div>
    	</div>
	        

	        <!-- {{ form.as_p }} -->
    </form> 
</div>



{% endblock %}

gap/templates/gap/graficos.html
{% extends "gap/base.html" %}


{% block content %}
<div class="container">
<form method="post" enctype="multipart/form-data">
<div class="card">
  <div class="card-header">
    Muestra de resultados
  </div>
  <div class="card-body">
  	<div class="input-group mb-3 col-md-6 col-xs-12">
	  	<div class="input-group-prepend">
	    	<label class="input-group-text" for="inputGroupSelect01">Encuesta</label>
	  	</div>
	  	<select class="custom-select" name="selectorencuesta">
        {% if encuestas %}
            {% for encuesta in encuestas %}
		    <option value = {{ encuesta.pk }}>{{ encuesta }}</option>
            {% endfor %}
        {% endif %}
	  	</select>
  	</div>
  	<div class="col-12 mb-3">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary"> Actualizar</button>

	</div>
    {% if values %}
	<div class="col-12">
		<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto" class="border"></div>
	</div>
    {% endif %}

  </div>
</div>
</form>
</div>

<script>
      _categories = {{categories|safe}};
      _values = {{values|safe}};

      Highcharts.chart('container', {
	  chart: {
              type: 'column'
	  },
	  title: {
              text: 'Porcentaje de complimiento por dominio'
	  },
	  subtitle: {
              text: ''
	  },
	  xAxis: {
            type: 'category'
        },
	  yAxis: {
              min: 0,
              title: {
		  text: 'Cumplimiento'
              }
	  },
	  tooltip: {
              headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
              pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
		  '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
              footerFormat: '</table>',
              shared: true,
              useHTML: true
	  },
	  plotOptions: {
              column: {
		  pointPadding: 0.2,
		  borderWidth: 0
        }
	  },
	  series: [{
              name: 'Cumplimiento',
              data: [
                  {% for value in values %}
                  {
                  name: '{{value.0}}',
                  y: {{value.1}},
                  drilldown: '{{value.0}}'
              },
                  {% endfor  %}


              ]

	  }],
          drilldown: {
    series: [
        {% for value in values %}
        {
        id: '{{value.0}}',

        data: [
            {% for pregunta in value.2 %}
                {
                 name: 'Pregunta {{ pregunta.0 }}',
                    y: {{ pregunta.1 }},
                    },
            {% endfor %}

        ]

    },
        {% endfor %}

    ]
}


      });
      </script>

{% endblock %}

gap/templates/gap/plan_de_accion.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">



<div class="container">
<form method="post" enctype="multipart/form-data">
<div class="card">
  <div class="card-header">
    Plan de Accion
  </div>
  <div class="card-body">
  	<div class="col-12 mb-3">

	</div>

		<div class="col-12">
			<p class="card-text"></p>
		</div>
	<div class="col-12">
		<table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Dominio</th>
                <th>Prioridad</th>
                <th>Duracion</th>
                <th>Responsable</th>
                <th>Plan de accion</th>
                <th>Plazo de inicio</th>
                <th>Plazo de finalización</th>
            </tr>
        </thead>
        <tbody>

            {% if dominios %}
                {% for Dominio in dominios %}
            <tr>
                <td>{{ Dominio.0 }}</td>
                <td>{{ Dominio.1 }}</td>
                <td>{{ Dominio.2 }}</td>
                <td>{{ Dominio.3 }}</td>
                <td>{{ Dominio.4 }}</td>
                <td>{{ Dominio.5 }}</td>
                <td>{{ Dominio.6 }}</td>
            </tr>
                {% endfor %}
            {% endif  %}
        </tbody>
    </table>
	</div>

  </div>
</div>
</form>
</div>

gap/templates/gap/pregunta_detail.html
{% extends "gap/base.html" %}

gap/templates/gap/pregunta_form.html
{% extends 'gap/base.html' %}
{% load bootstrap4 %}


{% block content %}
<div class="container">
    <h1 class="text-center">Crear Preguntas</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary" ><i class="fas fa-trash-alt"></i> Enviar</button>
    </form>
</div>
{% endblock %}

gap/templates/gap/pregunta_list.html
{% extends "gap/base.html" %}


{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-10 col-md-8 col-sm-12 text-center" ><h1>Listado de preguntas</h1>
    </div>
    <!-- {% if perms.catalog.add_book %} -->
    <div class="col-lg-2 col-md-4 col-sm-12 mb-2 text-center">
      <a href="{% url 'gap:pregunta_new' %}">
      <button type="button" class="btn btn-success">Agregar Pregunta</button>
      </a>
    </div>
    <!-- {% endif %} -->
  </div>

  {% if pregunta_list %}


  <div class="row">
    {% for pregunta in pregunta_list %}
    <div class="col-lg-4 col-md-6 col-sm-12 d-flex">

      
      <div class="card my-2 flex-fill">
        <div class="row no-gutters">
          <div class="col-lg-4 col-md-4 col-sm-1">
            </div>
          <div class="col-lg-8 col-md-8 col-sm-11">
            <div class="card-body">
              <h5 class="card-title"><a href="{{ pregunta.get_absolute_url }}">{{pregunta.question_text}}</a></h5>
              <p class="card-text">{{pregunta.dominio.nombre}}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    
    {% endfor %}
    </div>

    {% else %}
      <p>No hay preguntas disponibles</p>
    {% endif %}       
  </div>
{% endblock %}